In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('C:/Users/Yash Phadke/OneDrive/Desktop/ML/Logisitic regression/breast_cancer.csv')
test = df.pop('Class')
train = df.to_numpy()
df.head()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
0                5                        1                         1   
1                5                        4                         4   
2                3                        1                         1   
3                6                        8                         8   
4                4                        1                         1   

   Marginal Adhesion  Single Epithelial Cell Size  Bare Nuclei  \
0                  1                            2            1   
1                  5                            7           10   
2                  1                            2            2   
3                  1                            3            4   
4                  3                            2            1   

   Bland Chromatin  Normal Nucleoli  Mitoses  
0                3                1        1  
1                3                2        1  
2                3                1        1  
3                3                7        1  
4                3                1        1

In [3]:
test.head()

0    2
1    2
2    2
3    2
4    2
Name: Class, dtype: int64

In [4]:
test.unique()

array([2, 4], dtype=int64)

In [5]:
df.shape

(683, 9)

Here we define the loss function for this logistic regression . It's name is BinaryCrossEntropy and it's found by
$$
\ J = [(1-y)log(1-f(z)) + ylog(f(z))]
$$

However here z is also a function of the dot product of weights and input added to the biases
$$
\ z = \frac{1}{(1 + e^{-(\overrightarrow{W}.\overrightarrow{X}+\overrightarrow{B})})}
$$

In [6]:
def Sig(z):
    return 1/(1 + np.exp(-z))

In [7]:
def Predict(x,w,b):
    y_hat = np.dot(w,x) + b 
    y_hat = Sig(y_hat)
    if y_hat > 0.5:
        out = 4
    if y_hat < 0.5:
        out = 2
    return out

In [8]:
def Loss(x,y):
    if(y == 2):
        c = 0
    else:
        c = 1
    l = (c)*np.log(x) + (1-c)*np.log(1-x)
    return l

In [9]:
def Cost(x,y,w,b):
    m,n = x.shape
    loss = 0
    for i in range (m):
        temp = np.dot(w,x[i]) + b
        t = Sig(temp)
        loss += Loss(t,y[i])
    return loss/(2*m)

first we will do a simple foward prop 

In [13]:
weights = np.random.uniform(-0.1,0.1,(9,))
bias = np.random.uniform(-0.1,0.1,(1,))
print(bias)
print(weights)

[0.07770331]
[-0.03843164  0.00565274 -0.07999815  0.06256942  0.03807318  0.09591352
 -0.05291573  0.0639489   0.0175185 ]


In [14]:
Predict(train[0],weights,bias)

2

In [15]:
Cost(train,test,weights,bias)

array([-0.32470361])

In [16]:
def Gradient(x,y,w,b):
    m,n = x.shape
    bias = 0
    gradient = np.zeros(9,)
    for i in range(500):
        if(y[i] == 2):
            y[i] = 0
        else:
            y[i] == 1
        for j in range(n):
            gradient[j] += (Sig(np.dot(w,x[i])+b) - y[i])*x[i,j]
            bias +=  (Sig(np.dot(w,x[i])+b) - y[i])
    final_gradient = gradient/500 
    final_bias = bias/500
    return final_gradient, final_bias

In [17]:
Gradient(train,test,weights,bias)

(array([-8.77406652, -7.86589036, -7.98623771, -6.54007294, -6.37520623,
        -9.61784872, -6.68824009, -7.14295116, -3.21890139]),
 array([-8.88935543]))

In [32]:
def Grad_desc(x,y,w,b):
    temp_w = np.zeros(9,)
    m,n = x.shape
    alpha = 0.000005
    for i in range(1000):  #epochs 
        for j in range(n):
            temp_w[j] = w[j] + alpha*Gradient(x,y,w,b)[0][j]
            temp_b = b + alpha*Gradient(x,y,w,b)[1]
        w = temp_w
        b = temp_b
        if i%20 ==0:
            z = Cost(x,y,w,b)
            print("no of epochs:",i," cost :",z)
    return w,b
    

In [33]:
Gradient(train,test,weights,bias)[0][0]

-8.774066520646457

In [34]:
model_weights, model_bias = Grad_desc(train,test,weights,bias)

no of epochs: 0  cost : [-0.29090284]
no of epochs: 20  cost : [-0.29393036]
no of epochs: 40  cost : [-0.29704708]
no of epochs: 60  cost : [-0.30025494]
no of epochs: 80  cost : [-0.30355591]
no of epochs: 100  cost : [-0.3069519]
no of epochs: 120  cost : [-0.31044484]
no of epochs: 140  cost : [-0.31403661]
no of epochs: 160  cost : [-0.31772909]
no of epochs: 180  cost : [-0.32152408]
no of epochs: 200  cost : [-0.32542339]
no of epochs: 220  cost : [-0.32942875]
no of epochs: 240  cost : [-0.33354184]
no of epochs: 260  cost : [-0.33776429]
no of epochs: 280  cost : [-0.34209766]
no of epochs: 300  cost : [-0.34654343]
no of epochs: 320  cost : [-0.35110301]
no of epochs: 340  cost : [-0.35577772]
no of epochs: 360  cost : [-0.36056879]
no of epochs: 380  cost : [-0.36547735]
no of epochs: 400  cost : [-0.37050442]
no of epochs: 420  cost : [-0.37565094]
no of epochs: 440  cost : [-0.3809177]
no of epochs: 460  cost : [-0.3863054]
no of epochs: 480  cost : [-0.39181461]
no of epo

In [29]:
i = 30
z= 90
print("no of epochs:",i," cost :",z)

no of epochs: 30  cost : 90


In [18]:
def Accuracy(w,b):
    i = 500
    correct = 0
    wrong = 0
    while i < 683:
        y_pred = Predict(train[i],w,b)
        if(y_pred == test[i]):
            correct+=1
        else:
            wrong +=1
        i += 1
    ratio = correct /(correct + wrong)
    return ratio*100

In [38]:
before_training = Accuracy(weights,bias)
print(before_training)

32.78688524590164


In [37]:
after_training = Accuracy(model_weights,model_bias)
print(after_training)

77.04918032786885


In [41]:
Predict(train[0],model_weights,model_bias)

2