In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans

In [33]:
df = pd.read_csv('C:/Users/Yash Phadke/Onedrive/Desktop/ML/scikit-learn tutorials/Classification/College.csv')
df['Private'].replace(to_replace=['Yes','No'],value=[1,0],inplace= True)
df.drop("Unnamed: 0",axis=1,inplace=True)

In [34]:
df.head()

Private  Apps  Accept  Enroll  Top10perc  Top25perc  F.Undergrad  \
0        1  1660    1232     721         23         52         2885   
1        1  2186    1924     512         16         29         2683   
2        1  1428    1097     336         22         50         1036   
3        1   417     349     137         60         89          510   
4        1   193     146      55         16         44          249   

   P.Undergrad  Outstate  Room.Board  Books  Personal  PhD  Terminal  \
0          537      7440        3300    450      2200   70        78   
1         1227     12280        6450    750      1500   29        30   
2           99     11250        3750    400      1165   53        66   
3           63     12960        5450    450       875   92        97   
4          869      7560        4120    800      1500   76        72   

   S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0       18.1           12    7041         60  
1       12.2           16   10527         56  
2       12.9           30    8735         54  
3        7.7           37   19016         59  
4       11.9            2   10922         15

In [39]:
temp = df.to_numpy()

In [40]:
print(temp)

[[1.0000e+00 1.6600e+03 1.2320e+03 ... 1.2000e+01 7.0410e+03 6.0000e+01]
 [1.0000e+00 2.1860e+03 1.9240e+03 ... 1.6000e+01 1.0527e+04 5.6000e+01]
 [1.0000e+00 1.4280e+03 1.0970e+03 ... 3.0000e+01 8.7350e+03 5.4000e+01]
 ...
 [1.0000e+00 2.0970e+03 1.9150e+03 ... 2.0000e+01 8.3230e+03 4.9000e+01]
 [1.0000e+00 1.0705e+04 2.4530e+03 ... 4.9000e+01 4.0386e+04 9.9000e+01]
 [1.0000e+00 2.9890e+03 1.8550e+03 ... 2.8000e+01 4.5090e+03 9.9000e+01]]


In [41]:
X_train,X_cv = train_test_split(temp,test_size=0.2)

In [48]:
Kmeans = KMeans(n_clusters= 3, random_state= 0)
Kmeans.fit(X_train)

KMeans(n_clusters=3, random_state=0)

In [52]:
Kmeans.predict(X_cv)

AttributeError: 'NoneType' object has no attribute 'split'