In [68]:
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib as plt
import time

The data (X1, X2, X3, X4, X5, X6, X7) are for each city.

- X1 = total overall reported crime rate per 1 million residents
- X2 = reported violent crime rate per 100,000 residents
- X3 = annual police funding in $/resident
- X4 = % of people 25 years+ with 4 yrs. of high school
- X5 = % of 16 to 19 year-olds not in highschool and not highschool graduates.
- X6 = % of 18 to 24 year-olds in college
- X7 = % of people 25 years+ with at least 4 years of college

In [69]:
df = pd.read_csv('C:/Users/Yash Phadke/OneDrive/Desktop/ML/scikit-learn tutorials/Regression/main.csv') 
df.head()

X1   X2  X3  X4  X5  X6  X7
0  478  184  40  74  11  31  20
1  494  213  32  72  11  43  18
2  643  347  57  70  18  16  16
3  341  565  31  71  11  25  19
4  773  327  67  72   9  29  24

In [70]:
y = df.pop('X1')

In [71]:
df.head()

X2  X3  X4  X5  X6  X7
0  184  40  74  11  31  20
1  213  32  72  11  43  18
2  347  57  70  18  16  16
3  565  31  71  11  25  19
4  327  67  72   9  29  24

In [72]:
X_train,X_test,Y_train,Y_test = train_test_split(df,y,test_size =0.2)

In [73]:
scale = StandardScaler()
x_train = scale.fit_transform(X_train)
Y_1 = np.reshape(Y_train.values,(-1,1))
y_train = scale.fit_transform(Y_1)
x_test = scale.fit_transform(X_test)
Y_1 = np.reshape(Y_test.values,(-1,1))
y_test = scale.fit_transform(Y_1)

Ridge is used for regularised models where as for normal regression we use Linear Regression

In [74]:
model = linear_model.LinearRegression()
model.fit(x_train,y_train)
model.coef_
final = model.predict(x_test)
print(y_test)
print(final)

[[ 0.14560549]
 [-0.14515816]
 [-0.91680016]
 [ 1.29747689]
 [-0.67300602]
 [ 1.82532475]
 [-1.04428884]
 [-0.96824296]
 [ 1.10736219]
 [-0.62827315]]
[[-0.47971826]
 [-0.2477464 ]
 [-0.43333904]
 [ 0.35504306]
 [-0.21599875]
 [ 2.54952859]
 [-0.83273546]
 [-0.23022853]
 [-0.50095072]
 [ 0.0361455 ]]


In [75]:
model = linear_model.Ridge()
model.fit(x_train,y_train)
model.coef_
final = model.predict(x_test)
print(y_test)
print(final)

[[ 0.14560549]
 [-0.14515816]
 [-0.91680016]
 [ 1.29747689]
 [-0.67300602]
 [ 1.82532475]
 [-1.04428884]
 [-0.96824296]
 [ 1.10736219]
 [-0.62827315]]
[[-0.44550379]
 [-0.21317053]
 [-0.53164343]
 [ 0.31878823]
 [-0.21018128]
 [ 2.50000242]
 [-0.85479091]
 [-0.22900759]
 [-0.42449409]
 [ 0.09000095]]


In [76]:
model = linear_model.BayesianRidge()
model.fit(x_train,y_train)
model.coef_
final = model.predict(x_test)
print(y_test)
print(final)

[[ 0.14560549]
 [-0.14515816]
 [-0.91680016]
 [ 1.29747689]
 [-0.67300602]
 [ 1.82532475]
 [-1.04428884]
 [-0.96824296]
 [ 1.10736219]
 [-0.62827315]]
[-0.37877144 -0.12990145 -0.66825826  0.23082295 -0.18179981  2.28435211
 -0.82971985 -0.23638475 -0.26466481  0.1743253 ]


D:\anaconda\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
